force-app/main/default/objects/Account/fields/Jira_Project_Key__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Key__c</fullName>
    <label>Jira Project Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Jira_Project_Lead__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jira Project Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jira_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Name__c</fullName>
    <label>Jira Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Jira_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Jira_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>Jira User Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/JiraProjectWizardController.cls
/**
 * @description       : 
 * @author            : sebasgarcia
 * @group             : 
 * @last modified on  : 03-17-2025
 * @last modified by  : sebasgarcia
**/
public with sharing class JiraProjectWizardController {
    /**
    * @description true if jira project key has not been taken
    * @author sebasgarcia | 03-17-2025 
    * @param key 
    * @return Boolean 
    **/
    @AuraEnabled
    public static Boolean checkJiraKeyAvailable(String key){
        Boolean available = false;

        try {
            HttpResponse res = JiraCallout.getProject(key);

            if(res.getStatusCode() == 401) {
                throw new JiraException('Unauthorized with Jira');
            }

            available = res.getStatusCode() != 200;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return available;
    }

    /**
    * @description create Jira Project from the Account record page
    * @author sebasgarcia | 03-17-2025 
    * @param Key 
    * @param projectName 
    * @param accId 
    * @param userId 
    * @return Boolean 
    **/
    @AuraEnabled
    public static Boolean createProject(String Key, String projectName, Id accId, Id userId){
        Boolean success = false;
        Account acc = new Account();
        acc.id = accId;
        acc.Jira_Project_Key__c = key;
        acc.Jira_Project_Name__c = projectName;
        acc.Jira_Project_Lead__c = userId;
        User leadUser = [SELECT Id, Jira_User_Id__c from User WHERE id =: userId];
        String projectLeadId = leadUser.Jira_User_Id__c;
        try {
            JiraProjectHelper.createOrUpdateAccount(acc, projectLeadId);
            update acc;
            success = true;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        return success;
    }
}