force-app/main/default/objects/Account/fields/Jira_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Id__c</fullName>
    <externalId>true</externalId>
    <label>Jira Project Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Jira_Project_Key__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Key__c</fullName>
    <label>Jira Project Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Jira_Project_Lead__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jira Project Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jira_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Name__c</fullName>
    <label>Jira Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Jira_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Jira_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>Jira User Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/project/JiraProjectController.cls
/**
 * @description       : 
 * @author            : sebasgarcia
 * @group             : 
 * @last modified on  : 03-12-2025
 * @last modified by  : sebasgarcia
**/
public class JiraProjectController {
    public Id accId {get;set;}
    public Account acc {get;set;}
    
    public JiraProjectController(ApexPages.StandardController controller) {
        accId = controller.getRecord().Id;
        acc = [SELECT Id, Jira_Project_Key__c, Jira_Project_Id__c, Jira_Project_Name__c, Jira_Project_Lead__r.Jira_User_Id__c FROM Account WHERE Id =: accId];
    
        if(acc.Jira_Project_Lead__c== null){
            throw new JiraException('Account Jira Project Lead is empty.');
        }
    }
            
    
    
    public PageReference createProject(){
        try {
            JiraProjectHelper.createOrUpdateAccount(acc, '');
            update acc;
            
            return new PageReference('/'+ accId);
        } catch (JiraException e) {
            throw new JiraException('Problem Updating the Account');
        }
    
    }
}