force-app/main/default/objects/Account/fields/Jira_Project_Key__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Key__c</fullName>
    <label>Jira Project Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Jira_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Jira_Project_Name__c</fullName>
    <label>Jira Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/project/JiraProjectMapping.cls
/**
 * @description       : 
 * @author            : sebasgarcia
 * @group             : 
 * @last modified on  : 03-11-2025
 * @last modified by  : sebasgarcia
**/
public with sharing class JiraProjectMapping {

  public static JiraProjectJSON mapAccountToProject(Account acc, String projectLeadId) {
    JiraProjectJSON json = new JiraProjectJSON();
    json.name = acc.Jira_Project_Name__c;
    json.leadAccountId = projectLeadId;
    json.projectTypeKey = 'software';
    json.key = acc.Jira_Project_Key__c;

    return json;
  }
}