force-app/main/default/objects/Opportunity/fields/JIRA_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Id__c</fullName>
    <formula>Account.Jira_Project_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>JIRA Project Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/JIRA_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Version_Id__c</fullName>
    <label>JIRA Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/version/JiraVersionController.cls
/**
 * @description       : 
 * @author            : sebasgarcia
 * @group             : 
 * @last modified on  : 04-08-2025
 * @last modified by  : sebasgarcia
**/
public with sharing class JiraVersionController {

    @AuraEnabled
    public static void createVersion(Id oppId){
        try {
            Opportunity opp = [SELECT Id, Name, JIRA_Fix_Version_Name__c, JIRA_Project_Id__c, JIRA_Version_Id__c FROM Opportunity WHERE Id =: oppId];
            JiraVersionHelper.createVersion(opp);
            update opp;        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}