force-app/main/default/objects/Opportunity/fields/JIRA_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Id__c</fullName>
    <formula>Account.Jira_Project_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>JIRA Project Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/JIRA_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Version_Id__c</fullName>
    <label>JIRA Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/version/JiraVersionMapping.cls
/**
 * @description       : 
 * @author            : sebasgarcia
 * @group             : 
 * @last modified on  : 04-08-2025
 * @last modified by  : sebasgarcia
**/
public with sharing class JiraVersionMapping {

    public static JiraVersionJSON mapOpportunityToVersion(Opportunity opp) {
        JiraVersionJSON version = new JiraVersionJSON();
        version.name = opp.Jira_Fix_Version_Name__c;
        version.id = opp.Jira_Version_Id__c;
        version.description = opp.Name;
        if(String.isBlank(opp.Jira_Project_Id__c)) {
            throw new JiraException('Cannot create a version with the Jura Project ID null.');
        }

        version.projectId = Integer.valueOf(opp.Jira_Project_Id__c);
        return version;
    }

    public static Opportunity mapVersionToOpportunity(JiraVersionJSON version, Opportunity opp) {
        opp.Jira_Version_Id__c = String.valueOf(version.id);
        return opp; 
    }
}